# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  post:
    Aarchives: /archives
    Tags: /tags

# stylesheets loaded in the <head>
stylesheets:
  #global css
  - /css/Genso.css
  #layout css
  - /css/layout/layout.css
  - /css/layout/navigator.css
  - /css/layout/page-container.css
  - /css/layout/page-cover.css
  - /css/layout/slidebar.css
  - /css/layout/panel.css
  #index css
  - /css/index/index.css
  - /css/index/recommend-card-container.css
  - /css/index/card-container.css
  - /css/index/card.css

#raw source
rawSource: _source
# scripts loaded in the end of the body
scripts:
  - /js/Genso.js
  - /js/layout/page-cover.js
  - /js/layout/animation.js
  - /js/test.js
# config which js file will be loaded in a particular page
layout_scripts:
  - /js/layout/page-cover.js
  - /js/layout/animation.js

fonts:
  - /font/jf-openhuninn-2.0.ttf

color:
  card-title: "#000000"
