# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  post:
    Aarchives: /archives
    Tags: /tags

# stylesheets loaded in the <head>
stylesheets:
  #global css
  - /css/Genso.css
  #layout css
  - /css/layout/layout.css
  - /css/layout/navigator.css
  - /css/layout/page-container.css
  - /css/layout/page-cover.css
  - /css/layout/slidebar.css
  #index css
  - /css/index/index.css
  - /css/index/recommend-card-container.css
  - /css/index/card-container.css
  - /css/index/card.css
  #post css
  - /css/post/post.css
  - /css/post/idea.css
  #tool css
  - /css/tool/color.css

#raw source
rawSource: _source
# all scripts
scripts:
  - /js/Genso.js
  - /js/layout/animation.js
  - /js/layout/svg.js
  - /js/csstool.js
  - /js/post/mermaid.js
# config which js file will be loaded in a particular page
layout_scripts:
  - /js/layout/animation.js
  - /js/layout/svg.js
  - /js/csstool.js
post_scripts:
  - /js/post/mermaid.js
fonts:
  - /font/jf-openhuninn-2.0.ttf

color:
  card-title: "#000000"

recommend_card:
  title: Genso
  cover: https://s2.loli.net/2023/07/23/u9dvATztknGecmI.jpg
  article:
    - article_title: 百度一下
      url: www.baidu.com
    - article_title: google一下
      url: www.google.com

sociallink:
  github: https://github.com/DnullP

placard:
  - 这里是公告栏
  - 有什么东西可以写在这里
  - 然后展示一句很长很长很长很长很长很长很长很长很长很长很长很长很长很长的话