
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives

# stylesheets loaded in the <head>
stylesheets:
- /css/Genso.css
- /css/card.css
- /css/main-layout.css
- /css/left-container.css

# scripts loaded in the end of the body
scripts:
- /js/Genso.js
